### ISSUE TITLE
Example of not covered important reliability cases

### ISSUE THREAD

**Issue by marty-stranger** [junsolkar/tickets#1]
from test task definition: "please concentrate efforts to handle all possible edges cases (network delays, db or stripe outages)"
- https://github.com/junsolkar/tickets/blob/master/handler/charge_handler.go#L69
  - what if it fails because of network issues?
  - what if not enough funds on bank card?

**Comment by junsolkar** [comment]
stripe error handling has been implemented in the latest version of master branch 

charge_handler.go has been updated to handler to handler errors coming from stripe. if the type assertion of the error to stripe.Error is true, then we loop through to check the stripe error code and display an error message accordingly

if the assertion of stripe error to stripe.CardError or stripe.APIConnectionError is true then we display an error message with details as to what caused the error.
